import {
  Activity,
  BookText,
  Bot,
  Database,
  FileText,
  Flower2,
  Gauge,
  HardDrive,
  History,
  LineChart,
  ListChecks,
  MessageCircle,
  Newspaper,
  Notebook,
  Repeat,
  ShoppingBag,
  Table2,
  Terminal,
  Upload,
  UserRound,
  Users,
  UsersRound,
  Video,
  type LucideIcon,
} from 'lucide-react';

const icons: Record<string, LucideIcon> = {
  overview: Gauge,
  analysis: LineChart,
  customers: UserRound,
  identity: UsersRound,
  retention: Repeat,
  orders: Table2,
  upload: Upload,
  tasks: ListChecks,
  dictionary: BookText,
  sql: Terminal,
  reports: FileText,
  traffic: Activity,
  wechat: Newspaper,
  impact: ShoppingBag,
  xhs: Notebook,
  pgy: Flower2,
  zhihu: MessageCircle,
  channels: Video,
  users: Users,
  logs: History,
  database: HardDrive,
  collector: Bot,
};
export function navIcon(key: string): LucideIcon {
  return icons[key] ?? Database;
}
